services:
  backend:
    build:
      target: production
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - DB_CONNECTION_STRING=Server=db;Database=${MYSQL_DATABASE};User=${MYSQL_USER};Password=${MYSQL_PASSWORD};
    restart: unless-stopped

  frontend:
    build:
      target: production
    environment:
      - NODE_ENV=production
    restart: unless-stopped
