services:
  backend:
    build:
      target: production
    environment:
      - ASPNETCORE_ENVIRONMENT=staging
      - DB_CONNECTION_STRING=Server=db;Database=${MYSQL_DATABASE};User=${MYSQL_USER};Password=${MYSQL_PASSWORD};
      - JWT_KEY=${JWT_KEY}
      - JWT_ISSUER=${JWT_ISSUER}
      - JWT_AUDIENCE=${JWT_AUDIENCE}
      - JWT_EXPIRES_MINUTES=180
    restart: unless-stopped

  frontend:
    build:
      target: production
    environment:
      - NODE_ENV=production
    restart: unless-stopped
