services:
  backend:
    build:
      target: development
    volumes:
      - ./backend:/app
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    command: ["dotnet", "watch", "run", "--urls", "http://0.0.0.0:5182"]

  frontend:
    build:
      target: development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_DEV_SERVER_HOST=0.0.0.0
      - VITE_DEV_SERVER_HMR=true
    command: ["npx", "vite", "--host", "0.0.0.0"]
