name: Test

on:
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up testing environment for frontend
        run: |
          cd frontend
          # Installer avhengigheter basert på prosjekttype
          # For eksempel hvis det er Node.js:
          # npm install

      - name: Run frontend tests
        run: |
          cd frontend
          # Kjør testene dine
          # For eksempel:
          # npm test

      - name: Set up testing environment for backend
        run: |
          cd backend
          # Installer avhengigheter
          # npm install eller pip install -r requirements.txt

      - name: Run backend tests
        run: |
          cd backend
          # npm test eller pytest

      - name: Test frontend build
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: false
          load: true
          tags: frontend-test:pr

      - name: Test backend build
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: false
          load: true
          tags: backend-test:pr

      - name: Check image sizes
        run: |
          echo "Frontend image size:"
          docker image inspect frontend-test:pr --format='{{.Size}}' | awk '{print $1/1024/1024 " MB"}'

          echo "Backend image size:"
          docker image inspect backend-test:pr --format='{{.Size}}' | awk '{print $1/1024/1024 " MB"}'
