name: Test

on:
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up testing environment for frontend
        run: |
          cd frontend
          # Installer avhengigheter basert på prosjekttype
          # For eksempel hvis det er Node.js:
          # npm install

      - name: Run frontend tests
        run: |
          cd frontend
          # Kjør testene dine
          # For eksempel:
          # npm test

      - name: Set up testing environment for backend
        run: |
          cd backend
          # Installer avhengigheter
          # npm install eller pip install -r requirements.txt

      - name: Run backend tests
        run: |
          cd backend
          # npm test eller pytest

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and tag frontend Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          load: true
          tags: ${{ steps.login-ecr.outputs.registry }}/frontend-rasteplass:test

      - name: Build and tag backend Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          load: true
          tags: ${{ steps.login-ecr.outputs.registry }}/backend-rasteplass:test
